spring:


  datasource:
    url: jdbc:mariadb://192.0.200.233:3306/test3
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qwer1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace